### ISSUE TITLE
Création d'erreurs

### ISSUE THREAD

**Issue by loockeeer** [CamilleAbella/Debby#1]
Bonjour, j'ai essayé Debby une fois, et, il se trouve qu'un point m'a dérangé.

Les erreurs, je trouve que c'est dommage d'utiliser console.error, qui est plus un outil de débogage, au lieu de throw, qui permet d'avoir plus d'informations sur d'où provient l'erreur.

**Comment by loockeeer** [comment]
> 
> 
> Bonjour, j'ai essayé Debby une fois, et, il se trouve qu'un point m'a dérangé.
> 
> Les erreurs, je trouve que c'est dommage d'utiliser console.error, qui est plus un outil de débogage, au lieu de throw, qui permet d'avoir plus d'informations sur d'où provient l'erreur.

**Comment by GhomKrosmonaute** [comment]
J'aviserais de pencher à améliorer ceci.
Merci pour votre retour.
